clc
close all
clear

%% Calibrate basic parameters

calibr(1,0,0,0,0,2/3,2/3)
set_initval(1)

%% Baseline I
% no depreciation, one shock, optimise together

dynare baseline_asone.mod % set oneshock=1
% writematrix(A_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','B4')
% writematrix(C_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','C4')
% writematrix(Si_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','D4')
% writematrix(R_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','E4')
% writematrix(Y_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','F4')
% writematrix(Y_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','G4')
% writematrix(w_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','H4')
% writematrix(PI_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','I4')
% writematrix(PI_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','J4')
% writematrix(zeros(40,1),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','K4')
% writematrix(N_A_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','L4')
% writematrix(N_B_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','M4')
% writematrix(q_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','N4')
% writematrix(zeros(40,1),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','O4')
% writematrix(X_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','P4')
% writematrix(X_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','Q4')
% writematrix(GDP_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','R4')
% writematrix(PI_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','S4')
% 
% writematrix(A_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','B48')
% writematrix(C_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','C48')
% writematrix(Si_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','D48')
% writematrix(R_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','E48')
% writematrix(Y_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','F48')
% writematrix(Y_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','G48')
% writematrix(w_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','H48')
% writematrix(PI_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','I48')
% writematrix(PI_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','J48')
% writematrix(zeros(40,1)*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','K48')
% writematrix(N_A_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','L48')
% writematrix(N_B_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','M48')
% writematrix(q_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','N48')
% writematrix(zeros(40,1)*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','O48')
% writematrix(X_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','P48')
% writematrix(X_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','Q48')
% writematrix(GDP_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','R48')
% writematrix(PI_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','S48')
% 
% writematrix(A_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','B92')
% writematrix(C_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','C92')
% writematrix(Si_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','D92')
% writematrix(R_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','E92')
% writematrix(Y_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','F92')
% writematrix(Y_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','G92')
% writematrix(w_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','H92')
% writematrix(PI_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','I92')
% writematrix(PI_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','J92')
% writematrix(zeros(40,1)*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','K92')
% writematrix(N_A_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','L92')
% writematrix(N_B_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','M92')
% writematrix(q_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','N92')
% writematrix(zeros(40,1)*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','O92')
% writematrix(X_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','P92')
% writematrix(X_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','Q92')
% writematrix(GDP_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','R92')
% writematrix(PI_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','S92')
% 
% select={'A','C','Si','R','Y_G','Y_D','w_G','PI_G','PI_D','N_A','N_B','q','X_G','X_D','GDP','PI'}';
% writecell(select,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','U4')
% writematrix(oo_.steady_state(ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','V4')
% 
% writecell(select','D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','X3')
% writematrix(oo_.var(ismember(oo_.var_list,select),ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','X4')
% 
% writecell(select','D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','AQ3')
% writematrix(oo_.autocorr{1,1}(ismember(oo_.var_list,select),ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline I','Range','AQ4')
% 
% writematrix(R,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL I TS','Range','B4')
% writematrix(Y_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL I TS','Range','C4')
% writematrix(Y_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL I TS','Range','D4')
% writematrix(w_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL I TS','Range','E4')
% writematrix(PI_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL I TS','Range','F4')
% writematrix(PI_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL I TS','Range','G4')
% writematrix(N_A,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL I TS','Range','I4')
% writematrix(N_B,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL I TS','Range','J4')
% writematrix(q,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL I TS','Range','K4')
% writematrix(X_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL I TS','Range','M4')
% writematrix(X_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL I TS','Range','N4')
% writematrix(GDP,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL I TS','Range','O4')
% writematrix(PI,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL I TS','Range','P4')


disp('Baseline I done')

%% Baseline II
% no depreciation, one shock, optimise seperately

clear
dynare baseline.mod % set oneshock=1
% writematrix(A_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','B4')
% writematrix(C_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','C4')
% writematrix(Si_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','D4')
% writematrix(R_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','E4')
% writematrix(Y_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','F4')
% writematrix(Y_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','G4')
% writematrix(w_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','H4')
% writematrix(PI_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','I4')
% writematrix(PI_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','J4')
% writematrix(E_PI_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','K4')
% writematrix(N_A_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','L4')
% writematrix(N_B_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','M4')
% writematrix(q_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','N4')
% writematrix(E_q_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','O4')
% writematrix(X_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','P4')
% writematrix(X_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','Q4')
% writematrix(GDP_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','R4')
% writematrix(PI_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','S4')
% 
% writematrix(A_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','B48')
% writematrix(C_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','C48')
% writematrix(Si_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','D48')
% writematrix(R_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','E48')
% writematrix(Y_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','F48')
% writematrix(Y_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','G48')
% writematrix(w_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','H48')
% writematrix(PI_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','I48')
% writematrix(PI_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','J48')
% writematrix(E_PI_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','K48')
% writematrix(N_A_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','L48')
% writematrix(N_B_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','M48')
% writematrix(q_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','N48')
% writematrix(E_q_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','O48')
% writematrix(X_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','P48')
% writematrix(X_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','Q48')
% writematrix(GDP_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','R48')
% writematrix(PI_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','S48')
% 
% writematrix(A_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','B92')
% writematrix(C_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','C92')
% writematrix(Si_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','D92')
% writematrix(R_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','E92')
% writematrix(Y_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','F92')
% writematrix(Y_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','G92')
% writematrix(w_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','H92')
% writematrix(PI_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','I92')
% writematrix(PI_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','J92')
% writematrix(E_PI_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','K92')
% writematrix(N_A_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','L92')
% writematrix(N_B_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','M92')
% writematrix(q_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','N92')
% writematrix(E_q_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','O92')
% writematrix(X_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','P92')
% writematrix(X_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','Q92')
% writematrix(GDP_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','R92')
% writematrix(PI_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','S92')
% 
% select={'A','C','Si','R','Y_G','Y_D','w_G','PI_G','PI_D','E_PI_G','N_A','N_B','q','E_q','X_G','X_D','GDP','PI'}';
% writecell(select,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','U4')
% writematrix(oo_.steady_state(ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','V4')
% 
% writecell(select','D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','X3')
% writematrix(oo_.var(ismember(oo_.var_list,select),ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','X4')
% 
% writecell(select','D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','AQ3')
% writematrix(oo_.autocorr{1,1}(ismember(oo_.var_list,select),ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline II','Range','AQ4')
% 
% writematrix(R,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL II TS','Range','B4')
% writematrix(Y_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL II TS','Range','C4')
% writematrix(Y_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL II TS','Range','D4')
% writematrix(w_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL II TS','Range','E4')
% writematrix(PI_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL II TS','Range','F4')
% writematrix(PI_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL II TS','Range','G4')
% writematrix(N_A,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL II TS','Range','I4')
% writematrix(N_B,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL II TS','Range','J4')
% writematrix(q,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL II TS','Range','K4')
% writematrix(X_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL II TS','Range','M4')
% writematrix(X_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL II TS','Range','N4')
% writematrix(GDP,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL II TS','Range','O4')
% writematrix(PI,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL II TS','Range','P4')
% 

disp('Baseline II done')

%% Baseline III
% depreciation, together
clear
calibr(0.01,0,0,1.2,0.7,2/3,2/3)
close all

dynare baseline_asone.mod

% writematrix(A_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','B4')
% writematrix(C_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','C4')
% writematrix(Si_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','D4')
% writematrix(R_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','E4')
% writematrix(Y_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','F4')
% writematrix(Y_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','G4')
% writematrix(w_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','H4')
% writematrix(PI_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','I4')
% writematrix(PI_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','J4')
% writematrix(zeros(40,1),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','K4')
% writematrix(N_A_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','L4')
% writematrix(N_B_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','M4')
% writematrix(q_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','N4')
% writematrix(zeros(40,1),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','O4')
% writematrix(X_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','P4')
% writematrix(X_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','Q4')
% writematrix(GDP_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','R4')
% writematrix(PI_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','S4')
% 
% writematrix(A_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','B48')
% writematrix(C_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','C48')
% writematrix(Si_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','D48')
% writematrix(R_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','E48')
% writematrix(Y_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','F48')
% writematrix(Y_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','G48')
% writematrix(w_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','H48')
% writematrix(PI_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','I48')
% writematrix(PI_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','J48')
% writematrix(zeros(40,1)*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','K48')
% writematrix(N_A_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','L48')
% writematrix(N_B_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','M48')
% writematrix(q_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','N48')
% writematrix(zeros(40,1)*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','O48')
% writematrix(X_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','P48')
% writematrix(X_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','Q48')
% writematrix(GDP_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','R48')
% writematrix(PI_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','S48')
% 
% writematrix(A_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','B92')
% writematrix(C_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','C92')
% writematrix(Si_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','D92')
% writematrix(R_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','E92')
% writematrix(Y_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','F92')
% writematrix(Y_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','G92')
% writematrix(w_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','H92')
% writematrix(PI_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','I92')
% writematrix(PI_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','J92')
% writematrix(zeros(40,1)*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','K92')
% writematrix(N_A_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','L92')
% writematrix(N_B_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','M92')
% writematrix(q_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','N92')
% writematrix(zeros(40,1)*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','O92')
% writematrix(X_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','P92')
% writematrix(X_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','Q92')
% writematrix(GDP_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','R92')
% writematrix(PI_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','S92')
% 
% select={'A','C','Si','R','Y_G','Y_D','w_G','PI_G','PI_D','N_A','N_B','q','X_G','X_D','GDP','PI'}';
% writecell(select,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','U4')
% writematrix(oo_.steady_state(ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','V4')
% 
% writecell(select','D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','X3')
% writematrix(oo_.var(ismember(oo_.var_list,select),ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','X4')
% 
% writecell(select','D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','AQ3')
% writematrix(oo_.autocorr{1,1}(ismember(oo_.var_list,select),ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline III','Range','AQ4')
% 
% writematrix(R,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL III TS','Range','B4')
% writematrix(Y_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL III TS','Range','C4')
% writematrix(Y_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL III TS','Range','D4')
% writematrix(w_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL III TS','Range','E4')
% writematrix(PI_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL III TS','Range','F4')
% writematrix(PI_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL III TS','Range','G4')
% writematrix(N_A,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL III TS','Range','I4')
% writematrix(N_B,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL III TS','Range','J4')
% writematrix(q,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL III TS','Range','K4')
% writematrix(X_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL III TS','Range','M4')
% writematrix(X_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL III TS','Range','N4')
% writematrix(GDP,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL III TS','Range','O4')
% writematrix(PI,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL III TS','Range','P4')


disp('Baseline III done')

%% Baseline IV
% depreciation, seperately
clear
close all
dynare baseline.mod

% writematrix(A_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','B4')
% writematrix(C_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','C4')
% writematrix(Si_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','D4')
% writematrix(R_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','E4')
% writematrix(Y_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','F4')
% writematrix(Y_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','G4')
% writematrix(w_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','H4')
% writematrix(PI_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','I4')
% writematrix(PI_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','J4')
% writematrix(E_PI_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','K4')
% writematrix(N_A_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','L4')
% writematrix(N_B_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','M4')
% writematrix(q_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','N4')
% writematrix(E_q_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','O4')
% writematrix(X_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','P4')
% writematrix(X_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','Q4')
% writematrix(GDP_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','R4')
% writematrix(PI_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','S4')
% 
% writematrix(A_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','B48')
% writematrix(C_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','C48')
% writematrix(Si_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','D48')
% writematrix(R_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','E48')
% writematrix(Y_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','F48')
% writematrix(Y_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','G48')
% writematrix(w_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','H48')
% writematrix(PI_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','I48')
% writematrix(PI_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','J48')
% writematrix(E_PI_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','K48')
% writematrix(N_A_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','L48')
% writematrix(N_B_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','M48')
% writematrix(q_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','N48')
% writematrix(E_q_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','O48')
% writematrix(X_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','P48')
% writematrix(X_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','Q48')
% writematrix(GDP_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','R48')
% writematrix(PI_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','S48')
% 
% writematrix(A_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','B92')
% writematrix(C_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','C92')
% writematrix(Si_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','D92')
% writematrix(R_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','E92')
% writematrix(Y_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','F92')
% writematrix(Y_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','G92')
% writematrix(w_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','H92')
% writematrix(PI_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','I92')
% writematrix(PI_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','J92')
% writematrix(E_PI_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','K92')
% writematrix(N_A_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','L92')
% writematrix(N_B_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','M92')
% writematrix(q_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','N92')
% writematrix(E_q_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','O92')
% writematrix(X_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','P92')
% writematrix(X_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','Q92')
% writematrix(GDP_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','R92')
% writematrix(PI_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','S92')
% 
% writematrix(A_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','B136')
% writematrix(C_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','C136')
% writematrix(E_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','D136')
% writematrix(R_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','E136')
% writematrix(Y_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','F136')
% writematrix(Y_D_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','G136')
% writematrix(w_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','H136')
% writematrix(PI_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','I136')
% writematrix(PI_D_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','J136')
% writematrix(E_PI_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','K136')
% writematrix(N_A_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','L136')
% writematrix(N_B_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','M136')
% writematrix(q_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','N136')
% writematrix(E_q_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','O136')
% writematrix(X_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','P136')
% writematrix(X_D_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','Q136')
% writematrix(GDP_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','R136')
% writematrix(PI_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','S136')
% 
% writematrix(A_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','B180')
% writematrix(C_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','C180')
% writematrix(E_D_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','D180')
% writematrix(R_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','E180')
% writematrix(Y_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','F180')
% writematrix(Y_D_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','G180')
% writematrix(w_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','H180')
% writematrix(PI_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','I180')
% writematrix(PI_D_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','J180')
% writematrix(E_PI_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','K180')
% writematrix(N_A_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','L180')
% writematrix(N_B_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','M180')
% writematrix(q_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','N180')
% writematrix(E_q_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','O180')
% writematrix(X_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','P180')
% writematrix(X_D_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','Q180')
% writematrix(GDP_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','R180')
% writematrix(PI_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','S180')
% 
% select={'A','C','Si','R','Y_G','Y_D','w_G','PI_G','PI_D','E_PI_G','N_A','N_B','q','E_q','X_G','X_D','GDP','PI'}';
% writecell(select,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','U4')
% writematrix(oo_.steady_state(ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','V4')
% 
% writecell(select','D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','X3')
% writematrix(oo_.var(ismember(oo_.var_list,select),ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','X4')
% 
% writecell(select','D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','AQ3')
% writematrix(oo_.autocorr{1,1}(ismember(oo_.var_list,select),ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Baseline IV','Range','AQ4')
% 
% writematrix(R,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL IV TS','Range','B4')
% writematrix(Y_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL IV TS','Range','C4')
% writematrix(Y_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL IV TS','Range','D4')
% writematrix(w_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL IV TS','Range','E4')
% writematrix(PI_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL IV TS','Range','F4')
% writematrix(PI_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL IV TS','Range','G4')
% writematrix(N_A,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL IV TS','Range','I4')
% writematrix(N_B,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL IV TS','Range','J4')
% writematrix(q,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL IV TS','Range','K4')
% writematrix(X_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL IV TS','Range','M4')
% writematrix(X_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL IV TS','Range','N4')
% writematrix(GDP,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL IV TS','Range','O4')
% writematrix(PI,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','BL IV TS','Range','P4')
% 

disp('Baseline IV done')

%% Adapt I: Grocery prices higher volatility

% calibration
% %calibr(d,bg,bd,sigEG, sigED,phig,phid)
% phig=X(1);
% phid=X(2);
calibr(0.01,0,0,1.2,0.7,0.8,0) 

clear

close all
dynare baseline.mod

% writematrix(A_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','B4')
% writematrix(C_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','C4')
% writematrix(Si_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','D4')
% writematrix(R_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','E4')
% writematrix(Y_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','F4')
% writematrix(Y_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','G4')
% writematrix(w_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','H4')
% writematrix(PI_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','I4')
% writematrix(PI_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','J4')
% writematrix(E_PI_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','K4')
% writematrix(N_A_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','L4')
% writematrix(N_B_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','M4')
% writematrix(q_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','N4')
% writematrix(E_q_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','O4')
% writematrix(X_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','P4')
% writematrix(X_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','Q4')
% writematrix(GDP_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','R4')
% writematrix(PI_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','S4')
% 
% writematrix(A_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','B48')
% writematrix(C_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','C48')
% writematrix(Si_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','D48')
% writematrix(R_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','E48')
% writematrix(Y_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','F48')
% writematrix(Y_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','G48')
% writematrix(w_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','H48')
% writematrix(PI_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','I48')
% writematrix(PI_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','J48')
% writematrix(E_PI_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','K48')
% writematrix(N_A_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','L48')
% writematrix(N_B_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','M48')
% writematrix(q_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','N48')
% writematrix(E_q_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','O48')
% writematrix(X_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','P48')
% writematrix(X_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','Q48')
% writematrix(GDP_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','R48')
% writematrix(PI_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','S48')
% 
% writematrix(A_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','B92')
% writematrix(C_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','C92')
% writematrix(Si_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','D92')
% writematrix(R_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','E92')
% writematrix(Y_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','F92')
% writematrix(Y_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','G92')
% writematrix(w_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','H92')
% writematrix(PI_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','I92')
% writematrix(PI_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','J92')
% writematrix(E_PI_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','K92')
% writematrix(N_A_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','L92')
% writematrix(N_B_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','M92')
% writematrix(q_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','N92')
% writematrix(E_q_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','O92')
% writematrix(X_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','P92')
% writematrix(X_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','Q92')
% writematrix(GDP_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','R92')
% writematrix(PI_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','S92')
% 
% writematrix(A_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','B136')
% writematrix(C_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','C136')
% writematrix(E_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','D136')
% writematrix(R_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','E136')
% writematrix(Y_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','F136')
% writematrix(Y_D_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','G136')
% writematrix(w_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','H136')
% writematrix(PI_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','I136')
% writematrix(PI_D_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','J136')
% writematrix(E_PI_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','K136')
% writematrix(N_A_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','L136')
% writematrix(N_B_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','M136')
% writematrix(q_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','N136')
% writematrix(E_q_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','O136')
% writematrix(X_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','P136')
% writematrix(X_D_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','Q136')
% writematrix(GDP_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','R136')
% writematrix(PI_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','S136')
% 
% writematrix(A_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','B180')
% writematrix(C_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','C180')
% writematrix(E_D_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','D180')
% writematrix(R_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','E180')
% writematrix(Y_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','F180')
% writematrix(Y_D_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','G180')
% writematrix(w_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','H180')
% writematrix(PI_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','I180')
% writematrix(PI_D_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','J180')
% writematrix(E_PI_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','K180')
% writematrix(N_A_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','L180')
% writematrix(N_B_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','M180')
% writematrix(q_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','N180')
% writematrix(E_q_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','O180')
% writematrix(X_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','P180')
% writematrix(X_D_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','Q180')
% writematrix(GDP_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','R180')
% writematrix(PI_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','S180')
% 
% select={'A','C','Si','R','Y_G','Y_D','w_G','PI_G','PI_D','E_PI_G','N_A','N_B','q','E_q','X_G','X_D','GDP','PI'}';
% writecell(select,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','U4')
% writematrix(oo_.steady_state(ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','V4')
% 
% writecell(select','D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','X3')
% writematrix(oo_.var(ismember(oo_.var_list,select),ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','X4')
% 
% writecell(select','D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','AQ3')
% writematrix(oo_.autocorr{1,1}(ismember(oo_.var_list,select),ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt I','Range','AQ4')
% 
% writematrix(R,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A I TS','Range','B4')
% writematrix(Y_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A I TS','Range','C4')
% writematrix(Y_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A I TS','Range','D4')
% writematrix(w_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A I TS','Range','E4')
% writematrix(PI_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A I TS','Range','F4')
% writematrix(PI_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A I TS','Range','G4')
% writematrix(N_A,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A I TS','Range','I4')
% writematrix(N_B,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A I TS','Range','J4')
% writematrix(q,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A I TS','Range','K4')
% writematrix(X_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A I TS','Range','M4')
% writematrix(X_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A I TS','Range','N4')
% writematrix(GDP,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A I TS','Range','O4')
% writematrix(PI,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A I TS','Range','P4')

disp('Adapt I done')

%% Adapt II: Bias to Expectation_Gs
% average US food price inflation in the last decade has been 3%
set_initval(1)
clear
calibr(0.01,0.0338,0,1.2,0.7,2/3,2/3) 

close all
dynare baseline.mod

% writematrix(A_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','B4')
% writematrix(C_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','C4')
% writematrix(Si_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','D4')
% writematrix(R_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','E4')
% writematrix(Y_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','F4')
% writematrix(Y_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','G4')
% writematrix(w_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','H4')
% writematrix(PI_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','I4')
% writematrix(PI_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','J4')
% writematrix(E_PI_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','K4')
% writematrix(N_A_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','L4')
% writematrix(N_B_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','M4')
% writematrix(q_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','N4')
% writematrix(E_q_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','O4')
% writematrix(X_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','P4')
% writematrix(X_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','Q4')
% writematrix(GDP_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','R4')
% writematrix(PI_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','S4')
% 
% writematrix(A_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','B48')
% writematrix(C_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','C48')
% writematrix(Si_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','D48')
% writematrix(R_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','E48')
% writematrix(Y_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','F48')
% writematrix(Y_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','G48')
% writematrix(w_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','H48')
% writematrix(PI_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','I48')
% writematrix(PI_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','J48')
% writematrix(E_PI_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','K48')
% writematrix(N_A_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','L48')
% writematrix(N_B_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','M48')
% writematrix(q_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','N48')
% writematrix(E_q_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','O48')
% writematrix(X_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','P48')
% writematrix(X_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','Q48')
% writematrix(GDP_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','R48')
% writematrix(PI_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','S48')
% 
% writematrix(A_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','B92')
% writematrix(C_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','C92')
% writematrix(Si_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','D92')
% writematrix(R_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','E92')
% writematrix(Y_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','F92')
% writematrix(Y_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','G92')
% writematrix(w_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','H92')
% writematrix(PI_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','I92')
% writematrix(PI_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','J92')
% writematrix(E_PI_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','K92')
% writematrix(N_A_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','L92')
% writematrix(N_B_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','M92')
% writematrix(q_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','N92')
% writematrix(E_q_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','O92')
% writematrix(X_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','P92')
% writematrix(X_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','Q92')
% writematrix(GDP_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','R92')
% writematrix(PI_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','S92')
% 
% writematrix(A_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','B136')
% writematrix(C_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','C136')
% writematrix(E_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','D136')
% writematrix(R_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','E136')
% writematrix(Y_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','F136')
% writematrix(Y_D_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','G136')
% writematrix(w_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','H136')
% writematrix(PI_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','I136')
% writematrix(PI_D_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','J136')
% writematrix(E_PI_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','K136')
% writematrix(N_A_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','L136')
% writematrix(N_B_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','M136')
% writematrix(q_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','N136')
% writematrix(E_q_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','O136')
% writematrix(X_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','P136')
% writematrix(X_D_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','Q136')
% writematrix(GDP_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','R136')
% writematrix(PI_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','S136')
% 
% writematrix(A_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','B180')
% writematrix(C_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','C180')
% writematrix(E_D_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','D180')
% writematrix(R_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','E180')
% writematrix(Y_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','F180')
% writematrix(Y_D_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','G180')
% writematrix(w_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','H180')
% writematrix(PI_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','I180')
% writematrix(PI_D_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','J180')
% writematrix(E_PI_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','K180')
% writematrix(N_A_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','L180')
% writematrix(N_B_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','M180')
% writematrix(q_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','N180')
% writematrix(E_q_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','O180')
% writematrix(X_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','P180')
% writematrix(X_D_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','Q180')
% writematrix(GDP_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','R180')
% writematrix(PI_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','S180')
% 
% 
% select={'A','C','Si','R','Y_G','Y_D','w_G','PI_G','PI_D','E_PI_G','N_A','N_B','q','E_q','X_G','X_D','GDP','PI'}';
% writecell(select,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','U4')
% writematrix(oo_.steady_state(ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','V4')
% 
% writecell(select','D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','X3')
% writematrix(oo_.var(ismember(oo_.var_list,select),ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','X4')
% 
% writecell(select','D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','AQ3')
% writematrix(oo_.autocorr{1,1}(ismember(oo_.var_list,select),ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt II','Range','AQ4')
% 
% writematrix(R,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A II TS','Range','B4')
% writematrix(Y_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A II TS','Range','C4')
% writematrix(Y_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A II TS','Range','D4')
% writematrix(w_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A II TS','Range','E4')
% writematrix(PI_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A II TS','Range','F4')
% writematrix(PI_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A II TS','Range','G4')
% writematrix(N_A,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A II TS','Range','I4')
% writematrix(N_B,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A II TS','Range','J4')
% writematrix(q,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A II TS','Range','K4')
% writematrix(X_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A II TS','Range','M4')
% writematrix(X_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A II TS','Range','N4')
% writematrix(GDP,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A II TS','Range','O4')
% writematrix(PI,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A II TS','Range','P4')


disp('Adapt II done')

%% Adapt III: Bias to Expectation_Ds
% average US food price inflation in the last decade has been 3%
set_initval(1)
clear
calibr(0.01,0,0.02,1.2,0.7,2/3,2/3) 

close all
dynare baseline.mod

% writematrix(A_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','B4')
% writematrix(C_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','C4')
% writematrix(Si_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','D4')
% writematrix(R_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','E4')
% writematrix(Y_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','F4')
% writematrix(Y_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','G4')
% writematrix(w_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','H4')
% writematrix(PI_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','I4')
% writematrix(PI_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','J4')
% writematrix(E_PI_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','K4')
% writematrix(N_A_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','L4')
% writematrix(N_B_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','M4')
% writematrix(q_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','N4')
% writematrix(E_q_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','O4')
% writematrix(X_G_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','P4')
% writematrix(X_D_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','Q4')
% writematrix(GDP_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','R4')
% writematrix(PI_epsA*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','S4')
% 
% writematrix(A_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','B48')
% writematrix(C_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','C48')
% writematrix(Si_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','D48')
% writematrix(R_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','E48')
% writematrix(Y_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','F48')
% writematrix(Y_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','G48')
% writematrix(w_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','H48')
% writematrix(PI_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','I48')
% writematrix(PI_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','J48')
% writematrix(E_PI_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','K48')
% writematrix(N_A_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','L48')
% writematrix(N_B_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','M48')
% writematrix(q_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','N48')
% writematrix(E_q_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','O48')
% writematrix(X_G_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','P48')
% writematrix(X_D_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','Q48')
% writematrix(GDP_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','R48')
% writematrix(PI_epsC*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','S48')
% 
% writematrix(A_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','B92')
% writematrix(C_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','C92')
% writematrix(Si_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','D92')
% writematrix(R_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','E92')
% writematrix(Y_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','F92')
% writematrix(Y_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','G92')
% writematrix(w_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','H92')
% writematrix(PI_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','I92')
% writematrix(PI_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','J92')
% writematrix(E_PI_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','K92')
% writematrix(N_A_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','L92')
% writematrix(N_B_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','M92')
% writematrix(q_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','N92')
% writematrix(E_q_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','O92')
% writematrix(X_G_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','P92')
% writematrix(X_D_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','Q92')
% writematrix(GDP_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','R92')
% writematrix(PI_epsSi*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','S92')
% 
% writematrix(A_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','B136')
% writematrix(C_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','C136')
% writematrix(E_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','D136')
% writematrix(R_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','E136')
% writematrix(Y_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','F136')
% writematrix(Y_D_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','G136')
% writematrix(w_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','H136')
% writematrix(PI_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','I136')
% writematrix(PI_D_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','J136')
% writematrix(E_PI_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','K136')
% writematrix(N_A_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','L136')
% writematrix(N_B_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','M136')
% writematrix(q_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','N136')
% writematrix(E_q_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','O136')
% writematrix(X_G_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','P136')
% writematrix(X_D_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','Q136')
% writematrix(GDP_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','R136')
% writematrix(PI_epsE_G*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','S136')
% 
% writematrix(A_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','B180')
% writematrix(C_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','C180')
% writematrix(E_D_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','D180')
% writematrix(R_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','E180')
% writematrix(Y_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','F180')
% writematrix(Y_D_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','G180')
% writematrix(w_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','H180')
% writematrix(PI_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','I180')
% writematrix(PI_D_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','J180')
% writematrix(E_PI_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','K180')
% writematrix(N_A_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','L180')
% writematrix(N_B_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','M180')
% writematrix(q_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','N180')
% writematrix(E_q_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','O180')
% writematrix(X_G_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','P180')
% writematrix(X_D_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','Q180')
% writematrix(GDP_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','R180')
% writematrix(PI_epsE_D*100,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','S180')
% 
% select={'A','C','Si','R','Y_G','Y_D','w_G','PI_G','PI_D','E_PI_G','N_A','N_B','q','E_q','X_G','X_D','GDP','PI'}';
% writecell(select,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','U4')
% writematrix(oo_.steady_state(ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','V4')
% 
% writecell(select','D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','X3')
% writematrix(oo_.var(ismember(oo_.var_list,select),ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','X4')
% 
% writecell(select','D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','AQ3')
% writematrix(oo_.autocorr{1,1}(ismember(oo_.var_list,select),ismember(oo_.var_list,select)),'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','Adapt III','Range','AQ4')
% 
% writematrix(R,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A III TS','Range','B4')
% writematrix(Y_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A III TS','Range','C4')
% writematrix(Y_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A III TS','Range','D4')
% writematrix(w_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A III TS','Range','E4')
% writematrix(PI_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A III TS','Range','F4')
% writematrix(PI_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A III TS','Range','G4')
% writematrix(N_A,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A III TS','Range','I4')
% writematrix(N_B,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A III TS','Range','J4')
% writematrix(q,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A III TS','Range','K4')
% writematrix(X_G,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A III TS','Range','M4')
% writematrix(X_D,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A III TS','Range','N4')
% writematrix(GDP,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A III TS','Range','O4')
% writematrix(PI,'D:\Lovisa\Studium\Oxford\Department of Economics\Thesis\dynare\IRF_2.xlsx','Sheet','A III TS','Range','P4')


disp('Adapt III done')
